export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_USER_DETAIL_SUCCESS = 'UPDATE_USER_DETAIL_SUCCESS';
export const UPDATE_USER_DETAIL_FAILURE = 'UPDATE_USER_DETAIL_FAILURE';

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const FETCH_USER_FOR_HOME_SUCCESS = 'FETCH_USER_FOR_HOME_SUCCESS';
export const FETCH_USER_FOR_HOME_FAILURE = 'FETCH_USER_FOR_HOME_FAILURE';

export const FETCH_USER_FOR_UPDATE_SUCCESS = 'FETCH_USER_FOR_UPDATE_SUCCESS';
export const FETCH_USER_FOR_UPDATE_FAILURE = 'FETCH_USER_FOR_UPDATE_FAILURE';

export const TRACK_PLAYING_OR_PLAY_BUTTON_PRESSED = 'TRACK_PLAYING_OR_PLAY_BUTTON_PRESSED';
export const TRACK_PAUSED_OR_PAUSE_BUTTON_PRESSED = 'TRACK_PAUSED_OR_PAUSE_BUTTON_PRESSED';